# Generated by Django 6.1 on 2026-09-04

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenancy", "0002_tenantmembership"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantmembership",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tenantmembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("tenant_admin", "Tenant administrator"),
                    ("operator", "Operator"),
                    ("approver", "Approver"),
                    ("auditor", "Auditor"),
                    ("reader", "Reader"),
                ],
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="ExternalIdentity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("issuer", models.URLField(max_length=512)),
                ("subject", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ipms_external_identities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("issuer", "subject"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("issuer", "subject"),
                        name="unique_external_identity_subject",
                    ),
                    models.UniqueConstraint(
                        fields=("user", "issuer"),
                        name="unique_user_identity_issuer",
                    ),
                ],
            },
        ),
    ]
