# File Name: 0001_initial.py
# Version: v0.1.0 | Created: 2026-09-14 | Last Modified: 2026-09-14
# Author: Alice Endelgard | Organization: Alvestrasza Corporation
# Description: Add internal baseline assessment evidence; no initial/fabricated assessments.
# Generated by Django 6.1; reviewed additive schema.
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [
        ("agent_pki", "0011_lifecycle_authority_withdrawal"),
        ("discovery", "0024_software_windows_update_evidence"),
    ]
    operations = [
        migrations.CreateModel(
            name="BaselineAssessment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("baseline_id", models.CharField(max_length=96)),
                ("baseline_revision", models.CharField(blank=True, max_length=64)),
                ("catalog_revision", models.CharField(max_length=32)),
                ("profile", models.CharField(max_length=24)),
                ("os_build", models.CharField(max_length=64)),
                ("operating_system", models.CharField(max_length=255)),
                ("scope_verified", models.BooleanField(default=False)),
                ("total_controls", models.PositiveIntegerField(default=0)),
                ("passed_controls", models.PositiveIntegerField(default=0)),
                ("failed_controls", models.PositiveIntegerField(default=0)),
                ("unknown_controls", models.PositiveIntegerField(default=0)),
                ("not_applicable_controls", models.PositiveIntegerField(default=0)),
                ("error_code", models.CharField(blank=True, choices=[("", "None"), ("collection_failed", "Collection failed"), ("access_denied", "Access denied"), ("unsupported", "Unsupported")], max_length=32)),
                ("observed_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("enrollment", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="agent_pki.agentenrollment")),
                ("system", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="baseline_assessments", to="discovery.windowsserver")),
            ],
            options={
                "ordering": ("-observed_at", "-created_at", "-id"),
                "indexes": [models.Index(fields=["system", "baseline_id", "-observed_at"], name="security_system_baseline_idx")],
                "constraints": [models.CheckConstraint(
                    condition=models.Q(total_controls=models.F("passed_controls") + models.F("failed_controls") + models.F("unknown_controls") + models.F("not_applicable_controls")),
                    name="security_control_counts_match",
                )],
            },
        ),
    ]
