# File Name: 0004_domain_gpo_pilots.py
# Version: v0.1.0 | Created: 2026-09-14 | Last Modified: 2026-09-14
# Author: Alice Endelgard | Organization: Alvestrasza Corporation
# Description: Add tenant domain settings, authenticated executor reports and fenced pilot jobs.
# Generated by Django 6.1 on 2026-09-14 15:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_pki', '0011_lifecycle_authority_withdrawal'),
        ('discovery', '0024_software_windows_update_evidence'),
        ('security', '0003_native_baseline_scans'),
        ('tenancy', '0005_username_reservation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GpoExecutorReport',
            fields=[
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='agent_pki.agentenrollment')),
                ('agent_version', models.CharField(max_length=32)),
                ('domain_dns_name', models.CharField(blank=True, max_length=253)),
                ('domain_guid', models.CharField(blank=True, max_length=36)),
                ('forest_dns_name', models.CharField(blank=True, max_length=253)),
                ('dc_fqdn', models.CharField(blank=True, max_length=253)),
                ('role', models.CharField(max_length=40)),
                ('gpmc_available', models.BooleanField(default=False)),
                ('result_code', models.CharField(max_length=48)),
                ('observed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DomainSecuritySettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain_name', models.CharField(max_length=253)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('tier_ous', models.JSONField(default=dict)),
                ('gpo_name_template', models.CharField(max_length=160)),
                ('baseline_order', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
            ],
            options={
                'ordering': ('domain_name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='GpoImportJob',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('domain_guid', models.CharField(max_length=36)),
                ('request_sha256', models.CharField(max_length=64)),
                ('input_digest', models.CharField(max_length=64)),
                ('assignment', models.JSONField()),
                ('pilot_display_name', models.CharField(max_length=240)),
                ('pilot_name_key', models.CharField(max_length=240)),
                ('status', models.CharField(default='queued', max_length=32)),
                ('error_code', models.CharField(blank=True, max_length=48)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('claimed_at', models.DateTimeField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('gpo_guid', models.CharField(blank=True, max_length=36)),
                ('result_digest', models.CharField(blank=True, max_length=64)),
                ('result_evidence', models.JSONField(blank=True, default=dict)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='security.domainsecuritysettings')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agent_pki.agentenrollment')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='discovery.windowsserver')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
            ],
            options={
                'ordering': ('-requested_at', '-id'),
            },
        ),
        migrations.AddConstraint(
            model_name='domainsecuritysettings',
            constraint=models.UniqueConstraint(fields=('tenant', 'domain_name'), name='security_tenant_domain'),
        ),
        migrations.AddIndex(
            model_name='gpoimportjob',
            index=models.Index(fields=['enrollment', 'status'], name='security_gpo_agent_status'),
        ),
        migrations.AddConstraint(
            model_name='gpoimportjob',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('queued', 'awaiting_approval', 'running', 'reconciliation_required'))), fields=('tenant', 'domain_guid'), name='security_gpo_domain_fence'),
        ),
        migrations.AddConstraint(
            model_name='gpoimportjob',
            constraint=models.UniqueConstraint(fields=('tenant', 'domain_guid', 'pilot_name_key'), name='security_gpo_pilot_identity'),
        ),
    ]
