# File Name: 0005_gpoapprovalpolicy_gpodomainauthorization_and_more.py
# Version: v0.1.0 | Created: 2026-09-15 | Last Modified: 2026-09-15
# Author: Alice Endelgard | Organization: Alvestrasza Corporation
# Description: Add central approval state while preserving legacy inserts with database defaults.
# Generated by Django 6.1 on 2026-09-15 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_domain_gpo_pilots'),
        ('tenancy', '0005_username_reservation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GpoApprovalPolicy',
            fields=[
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tenancy.tenant')),
                ('four_eyes_required', models.BooleanField(db_default=False, default=False)),
                ('revision', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='GpoDomainAuthorization',
            fields=[
                ('domain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='security.domainsecuritysettings')),
                ('revision', models.PositiveIntegerField(default=1)),
                ('grants', models.JSONField(default=list)),
            ],
        ),
        migrations.AddField(
            model_name='gpoimportjob',
            name='approval_digest',
            field=models.CharField(blank=True, db_default='', max_length=64),
        ),
        migrations.AddField(
            model_name='gpoimportjob',
            name='approved_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='gpoimportjob',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_gpo_import_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gpoimportjob',
            name='authorization_revision',
            field=models.PositiveIntegerField(db_default=1, default=1),
        ),
        migrations.AddField(
            model_name='gpoimportjob',
            name='four_eyes_required',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name='gpoimportjob',
            name='policy_revision',
            field=models.PositiveIntegerField(db_default=1, default=1),
        ),
    ]
