# File Name: 0008_gpo_overrides.py
# Version: v0.1.0 | Created: 2026-09-16 | Last Modified: 2026-09-16
# Author: Alice Endelgard | Organization: Alvestrasza Corporation
# Description: Add tenant sparse override definitions and distinct managed GPO identities.
# Generated by Django 6.1 on 2026-09-16 08:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0007_gpo_reconciliation'),
        ('tenancy', '0005_username_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='GpoOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('baseline_id', models.CharField(max_length=96)),
                ('backup_id', models.CharField(max_length=38)),
                ('artifact_sha256', models.CharField(max_length=64)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('enabled', models.BooleanField(default=True)),
                ('entries', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
            ],
            options={
                'ordering': ('name', 'id'),
            },
        ),
        migrations.AddField(
            model_name='managedgpopolicy',
            name='override',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='security.gpooverride'),
        ),
    ]
