# File Name: 0001_initial.py
# Version: v0.1.0
# Created: 2026-09-13
# Last Modified: 2026-09-13
# Author: Alice Endelgard
# Organization: Alvestrasza Corporation
# Description: Initial source and WSUS metadata schema; generated by Django 6.1.

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0005_username_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('scope', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('token_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='WsusSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_id', models.UUIDField()),
                ('digest', models.CharField(max_length=64)),
                ('observed_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('updates', models.JSONField(default=list)),
                ('computer_count', models.PositiveIntegerField()),
                ('update_count', models.PositiveIntegerField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='updates.updatesource')),
            ],
        ),
        migrations.CreateModel(
            name='WsusComputerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_id', models.UUIDField()),
                ('fqdn', models.CharField(max_length=253)),
                ('reported_at', models.DateTimeField(null=True)),
                ('updates', models.JSONField(default=list)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computers', to='updates.wsussnapshot')),
            ],
        ),
        migrations.AddField(
            model_name='updatesource',
            name='current_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='updates.wsussnapshot'),
        ),
        migrations.AddConstraint(
            model_name='wsussnapshot',
            constraint=models.UniqueConstraint(fields=('source', 'snapshot_id'), name='unique_wsus_source_snapshot'),
        ),
        migrations.AddIndex(
            model_name='wsuscomputerreport',
            index=models.Index(fields=['snapshot', 'fqdn'], name='wsus_snapshot_fqdn_idx'),
        ),
        migrations.AddConstraint(
            model_name='wsuscomputerreport',
            constraint=models.UniqueConstraint(fields=('snapshot', 'computer_id'), name='unique_wsus_snapshot_computer'),
        ),
    ]
