# File Name: 0001_initial.py
# Version: v0.1.0 | Created: 2026-09-19 | Last Modified: 2026-09-19
# Author: Alice Endelgard | Organization: Alvestrasza Corporation
# Description: Immutable HGS plan, node binding and durable step schema.
# Generated by Django 6.1 on 2026-09-19 11:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent_pki', '0011_lifecycle_authority_withdrawal'),
        ('discovery', '0024_software_windows_update_evidence'),
        ('tenancy', '0006_tenant_purpose'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HgsDeployment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('profile', models.CharField(max_length=16)),
                ('attestation_mode', models.CharField(max_length=16)),
                ('domain_name', models.CharField(max_length=253)),
                ('service_name', models.CharField(max_length=63)),
                ('config', models.JSONField(default=dict)),
                ('plan_digest', models.CharField(max_length=64)),
                ('status', models.CharField(default='draft', max_length=32)),
                ('approved_at', models.DateTimeField(null=True)),
                ('plan_expires_at', models.DateTimeField()),
                ('approval_expires_at', models.DateTimeField(null=True)),
                ('authority_revoked_at', models.DateTimeField(null=True)),
                ('blockers', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hgs_approvals', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hgs_plans', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='HgsNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_uri', models.CharField(max_length=64)),
                ('hostname', models.CharField(max_length=255)),
                ('ordinal', models.PositiveSmallIntegerField()),
                ('role', models.CharField(max_length=16)),
                ('status', models.CharField(default='pending', max_length=32)),
                ('readiness', models.JSONField(null=True)),
                ('blockers', models.JSONField(default=list)),
                ('observed_at', models.DateTimeField(null=True)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nodes', to='hgs.hgsdeployment')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agent_pki.agentenrollment')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='discovery.windowsserver')),
            ],
            options={
                'ordering': ('ordinal',),
            },
        ),
        migrations.CreateModel(
            name='HgsJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(max_length=24)),
                ('sequence', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(default='queued', max_length=32)),
                ('assignment', models.JSONField(default=dict)),
                ('receipt', models.JSONField(null=True)),
                ('result_code', models.CharField(blank=True, max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offered_at', models.DateTimeField(null=True)),
                ('claimed_at', models.DateTimeField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='hgs.hgsdeployment')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='hgs.hgsnode')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='hgsdeployment',
            index=models.Index(fields=['tenant', 'status'], name='hgs_plan_tenant_status'),
        ),
        migrations.AddConstraint(
            model_name='hgsnode',
            constraint=models.UniqueConstraint(fields=('deployment', 'ordinal'), name='hgs_node_ordinal_unique'),
        ),
        migrations.AddConstraint(
            model_name='hgsnode',
            constraint=models.UniqueConstraint(fields=('deployment', 'enrollment'), name='hgs_node_enrollment_unique'),
        ),
        migrations.AddConstraint(
            model_name='hgsjob',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('queued', 'offered', 'running', 'waiting_for_reboot'))), fields=('node',), name='hgs_one_active_node_job'),
        ),
    ]
