from django.urls import include, path
from ipms.apps.tenancy.platform_views import (
    PlatformTenantListCreateView,
    PlatformTenantDetailView,
    InitialTenantAdministratorView,
)
from ipms.apps.agent_pki.native_views import NativeConsoleConfigurationView
from ipms.apps.agent_pki.service_account_views import (
    ServiceAccountListView,
    ServiceAccountDetailView,
    ServiceAccountHostListView,
    ServiceAccountHostDetailView,
)

from ipms.apps.agent_pki.views import (
    AgentAdministrationDetailView,
    AgentAdministrationListView,
    AgentLifecycleView,
    LinuxAgentEnrollmentView,
    WindowsAgentDeploymentDetailView,
    WindowsAgentDeploymentListCreateView,
    WindowsAgentDeploymentPreflightView,
)

from ipms.apps.discovery.views import (
    BmcCertificateProbeView,
    BmcCommunicationLogExportView,
    BmcCommunicationLogListView,
    BmcEventLogEntryListView,
    BmcEventLogEntryExportView,
    BmcConnectorEnrollmentView,
    ConnectorCredentialView,
    ConnectorDetailView,
    ConnectorDiscoveryView,
    ConnectorEndpointListView,
    PhysicalSystemListView,
    HyperVVirtualMachineListView,
    HyperVVirtualMachineActionJobView,
    HyperVVirtualMachineActionView,
    HyperVConsoleFrameView,
    HyperVConsoleInputView,
    HyperVConsoleSessionCreateView,
    HyperVConsoleSessionView,
    LinuxSystemDetailView,
    LinuxSystemListView,
    ManagedDeviceCertificateProbeView,
    ManagedDeviceEnrollmentView,
    ManagedInfrastructureDeviceListView,
    SoftwareInventorySnapshotListView,
    SoftwarePackageListView,
    WindowsServerDetailView,
    WindowsClientFamilyListView,
    WindowsServerListView,
    WindowsServerRoleListView,
    WindowsServerTelemetryView,
)

from . import views

app_name = "core"

urlpatterns = [
    path(
        "platform/tenants/",
        PlatformTenantListCreateView.as_view(),
        name="platform-tenant-list",
    ),
    path(
        "platform/tenants/<uuid:pk>/",
        PlatformTenantDetailView.as_view(),
        name="platform-tenant-detail",
    ),
    path(
        "platform/tenants/<uuid:pk>/initial-administrator/",
        InitialTenantAdministratorView.as_view(),
        name="platform-tenant-initial-administrator",
    ),
    path(
        "service-accounts/",
        ServiceAccountListView.as_view(),
        name="service-account-list",
    ),
    path(
        "service-accounts/hosts/",
        ServiceAccountHostListView.as_view(),
        name="service-account-host-list",
    ),
    path(
        "service-accounts/hosts/<uuid:pk>/",
        ServiceAccountHostDetailView.as_view(),
        name="service-account-host-detail",
    ),
    path(
        "service-accounts/<uuid:pk>/",
        ServiceAccountDetailView.as_view(),
        name="service-account-detail",
    ),
    path(
        "hyper-v/virtual-machines/<uuid:pk>/console-configuration/",
        NativeConsoleConfigurationView.as_view(),
        name="native-console-configuration",
    ),
    path("", views.api_information, name="api-information"),
    path("health/live/", views.liveness, name="liveness"),
    path("health/ready/", views.readiness, name="readiness"),
    path("auth/", include("ipms.apps.tenancy.urls")),
    path(
        "agents/windows/deployments/",
        WindowsAgentDeploymentListCreateView.as_view(),
        name="windows-agent-deployment-list",
    ),
    path(
        "agents/linux/enrollments/",
        LinuxAgentEnrollmentView.as_view(),
        name="linux-agent-enrollment",
    ),
    path(
        "agents/windows/deployments/preflight/",
        WindowsAgentDeploymentPreflightView.as_view(),
        name="windows-agent-deployment-preflight",
    ),
    path(
        "agents/windows/deployments/<uuid:pk>/",
        WindowsAgentDeploymentDetailView.as_view(),
        name="windows-agent-deployment-detail",
    ),
    path(
        "agents/",
        AgentAdministrationListView.as_view(),
        name="agent-administration-list",
    ),
    path(
        "agents/<uuid:pk>/",
        AgentAdministrationDetailView.as_view(),
        name="agent-administration-detail",
    ),
    path(
        "agents/<uuid:pk>/lifecycle/",
        AgentLifecycleView.as_view(),
        name="agent-lifecycle",
    ),
    path("connectors/", ConnectorEndpointListView.as_view(), name="connector-list"),
    path(
        "connectors/devices/",
        ManagedDeviceEnrollmentView.as_view(),
        name="managed-device-enroll",
    ),
    path(
        "connectors/devices/certificate/",
        ManagedDeviceCertificateProbeView.as_view(),
        name="managed-device-certificate",
    ),
    path(
        "managed-devices/",
        ManagedInfrastructureDeviceListView.as_view(),
        name="managed-device-list",
    ),
    path("connectors/bmc/", BmcConnectorEnrollmentView.as_view(), name="bmc-enroll"),
    path(
        "connectors/bmc/certificate/",
        BmcCertificateProbeView.as_view(),
        name="bmc-certificate-probe",
    ),
    path(
        "connectors/<uuid:pk>/",
        ConnectorDetailView.as_view(),
        name="connector-detail",
    ),
    path(
        "connectors/<uuid:pk>/credentials/",
        ConnectorCredentialView.as_view(),
        name="connector-credentials",
    ),
    path(
        "connectors/<uuid:pk>/discover/",
        ConnectorDiscoveryView.as_view(),
        name="connector-discover",
    ),
    path("physical-systems/", PhysicalSystemListView.as_view(), name="physical-list"),
    path(
        "windows-servers/", WindowsServerListView.as_view(), name="windows-server-list"
    ),
    path(
        "windows-server-roles/",
        WindowsServerRoleListView.as_view(),
        name="windows-server-role-list",
    ),
    path(
        "windows-client-families/",
        WindowsClientFamilyListView.as_view(),
        name="windows-client-family-list",
    ),
    path(
        "hyper-v/virtual-machines/",
        HyperVVirtualMachineListView.as_view(),
        name="hyperv-virtual-machine-list",
    ),
    path(
        "hyper-v/virtual-machines/<uuid:pk>/actions/",
        HyperVVirtualMachineActionView.as_view(),
        name="hyperv-virtual-machine-action",
    ),
    path(
        "hyper-v/actions/<uuid:pk>/",
        HyperVVirtualMachineActionJobView.as_view(),
        name="hyperv-virtual-machine-action-job",
    ),
    path(
        "hyper-v/virtual-machines/<uuid:pk>/console-sessions/",
        HyperVConsoleSessionCreateView.as_view(),
        name="hyperv-console-session-create",
    ),
    path(
        "hyper-v/console-sessions/<uuid:pk>/",
        HyperVConsoleSessionView.as_view(),
        name="hyperv-console-session",
    ),
    path(
        "hyper-v/console-sessions/<uuid:pk>/frame/",
        HyperVConsoleFrameView.as_view(),
        name="hyperv-console-frame",
    ),
    path(
        "hyper-v/console-sessions/<uuid:pk>/input/",
        HyperVConsoleInputView.as_view(),
        name="hyperv-console-input",
    ),
    path("linux-systems/", LinuxSystemListView.as_view(), name="linux-system-list"),
    path(
        "linux-systems/<uuid:pk>/",
        LinuxSystemDetailView.as_view(),
        name="linux-system-detail",
    ),
    path(
        "software-inventory/",
        SoftwareInventorySnapshotListView.as_view(),
        name="software-inventory-list",
    ),
    path(
        "software-inventory/<uuid:pk>/packages/",
        SoftwarePackageListView.as_view(),
        name="software-package-list",
    ),
    path(
        "windows-servers/<uuid:pk>/",
        WindowsServerDetailView.as_view(),
        name="windows-server-detail",
    ),
    path(
        "windows-servers/<uuid:pk>/telemetry/",
        WindowsServerTelemetryView.as_view(),
        name="windows-server-telemetry",
    ),
    path("bmc-logs/", BmcCommunicationLogListView.as_view(), name="bmc-log-list"),
    path(
        "bmc-event-logs/",
        BmcEventLogEntryListView.as_view(),
        name="bmc-event-log-list",
    ),
    path(
        "bmc-event-logs/export/",
        BmcEventLogEntryExportView.as_view(),
        name="bmc-event-log-export",
    ),
    path(
        "bmc-logs/export/",
        BmcCommunicationLogExportView.as_view(),
        name="bmc-log-export",
    ),
    path("discovery-jobs/", include("ipms.apps.discovery.urls")),
]
