# Generated by Django 6.1 on 2026-09-01 09:29

import django.db.models.deletion
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [("tenancy", "0002_tenantmembership")]
    operations = [
        migrations.CreateModel(
            name="AgentIssuer",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("status", models.CharField(choices=[("active", "Active"), ("overlap", "Overlap"), ("retired", "Retired")], default="active", max_length=16)),
                ("certificate_pem", models.TextField()),
                ("chain_pem", models.TextField()),
                ("fingerprint_sha256", models.CharField(max_length=64, unique=True)),
                ("serial_number", models.CharField(max_length=64)),
                ("private_key_nonce", models.BinaryField(blank=True, null=True)),
                ("private_key_ciphertext", models.BinaryField(blank=True, null=True)),
                ("key_version", models.PositiveSmallIntegerField(default=1)),
                ("external", models.BooleanField(default=False)),
                ("not_before", models.DateTimeField()),
                ("not_after", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="agent_issuers", to="tenancy.tenant")),
            ],
            options={"ordering": ("-created_at",)},
        ),
        migrations.CreateModel(
            name="AgentEnrollment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("device_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("device_uri", models.CharField(max_length=64, unique=True)),
                ("display_name", models.CharField(max_length=255)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("active", "Active"), ("revoked", "Revoked")], default="pending", max_length=16)),
                ("certificate_pem", models.TextField(blank=True)),
                ("certificate_fingerprint_sha256", models.CharField(blank=True, max_length=64)),
                ("certificate_serial_number", models.CharField(blank=True, max_length=64)),
                ("certificate_not_before", models.DateTimeField(blank=True, null=True)),
                ("certificate_not_after", models.DateTimeField(blank=True, null=True)),
                ("key_algorithm", models.CharField(blank=True, max_length=32)),
                ("first_inventory_at", models.DateTimeField(blank=True, null=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="agent_enrollments", to="tenancy.tenant")),
                ("issuer", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="enrollments", to="agent_pki.agentissuer")),
            ],
            options={"ordering": ("display_name",)},
        ),
        migrations.CreateModel(
            name="AgentPkiPolicy",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("trust_mode", models.CharField(choices=[("ipms_managed", "IPMS managed"), ("external_issuing_ca", "External issuing CA"), ("external_certificates", "External certificates")], max_length=32)),
                ("gateway_dns_name", models.CharField(max_length=253)),
                ("gateway_port", models.PositiveIntegerField(default=9419, validators=[django.core.validators.MinValueValidator(1024), django.core.validators.MaxValueValidator(65535)])),
                ("root_certificate_pem", models.TextField(blank=True)),
                ("root_fingerprint_sha256", models.CharField(blank=True, max_length=64)),
                ("root_recovery_exported_at", models.DateTimeField(blank=True, null=True)),
                ("certificate_lifetime_days", models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)])),
                ("renewal_window_days", models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="agent_pki_policy", to="tenancy.tenant")),
            ],
        ),
        migrations.AddField(model_name="agentissuer", name="policy", field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="issuers", to="agent_pki.agentpkipolicy")),
        migrations.CreateModel(
            name="AgentGatewayIdentity",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("certificate_pem", models.TextField()),
                ("chain_pem", models.TextField()),
                ("fingerprint_sha256", models.CharField(max_length=64, unique=True)),
                ("private_key_nonce", models.BinaryField()),
                ("private_key_ciphertext", models.BinaryField()),
                ("key_version", models.PositiveSmallIntegerField(default=1)),
                ("not_before", models.DateTimeField()),
                ("not_after", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("rotated_at", models.DateTimeField(blank=True, null=True)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="agent_gateway_identities", to="tenancy.tenant")),
                ("issuer", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="gateway_identities", to="agent_pki.agentissuer")),
                ("policy", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="gateway_identity", to="agent_pki.agentpkipolicy")),
            ],
        ),
        migrations.CreateModel(
            name="AgentRevocation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("certificate_serial_number", models.CharField(max_length=64)),
                ("reason", models.CharField(max_length=64)),
                ("revoked_by", models.CharField(max_length=255)),
                ("revoked_at", models.DateTimeField(auto_now_add=True)),
                ("enrollment", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="revocation", to="agent_pki.agentenrollment")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="agent_revocations", to="tenancy.tenant")),
            ],
            options={"ordering": ("-revoked_at",)},
        ),
        migrations.CreateModel(
            name="AgentEnrollmentToken",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("token_digest", models.CharField(max_length=64, unique=True)),
                ("gateway_fingerprint_sha256", models.CharField(max_length=64)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("enrollment", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="bootstrap_tokens", to="agent_pki.agentenrollment")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="agent_enrollment_tokens", to="tenancy.tenant")),
            ],
            options={"indexes": [models.Index(fields=["tenant", "expires_at"], name="agent_token_tenant_expiry")]},
        ),
        migrations.AddIndex(model_name="agentenrollment", index=models.Index(fields=["tenant", "status"], name="agent_enroll_tenant_status")),
        migrations.AddConstraint(model_name="agentenrollment", constraint=models.UniqueConstraint(fields=("tenant", "device_id"), name="unique_tenant_agent_device")),
        migrations.AddConstraint(model_name="agentissuer", constraint=models.UniqueConstraint(fields=("tenant", "serial_number"), name="unique_tenant_agent_issuer_serial")),
    ]
