# Generated by Django 6.1 on 2026-09-01 15:47

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent_pki", "0001_initial"),
        ("tenancy", "0002_tenantmembership"),
    ]

    operations = [
        migrations.CreateModel(
            name="WindowsAgentDeployment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("display_name", models.CharField(max_length=255)),
                ("target_address", models.CharField(max_length=253)),
                (
                    "target_port",
                    models.PositiveIntegerField(
                        default=5986,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(65535),
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("requested_by", models.CharField(max_length=255)),
                (
                    "certificate_fingerprint_sha256",
                    models.CharField(max_length=64),
                ),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "enrollment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="windows_deployment",
                        to="agent_pki.agentenrollment",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="windows_agent_deployments",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={"ordering": ("-created_at",)},
        ),
        migrations.CreateModel(
            name="WindowsAgentDeploymentSecret",
            fields=[
                (
                    "deployment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="secret",
                        serialize=False,
                        to="agent_pki.windowsagentdeployment",
                    ),
                ),
                ("nonce", models.BinaryField()),
                ("ciphertext", models.BinaryField()),
                ("key_version", models.PositiveSmallIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="windows_agent_deployment_secrets",
                        to="tenancy.tenant",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="windowsagentdeployment",
            index=models.Index(
                fields=["tenant", "-created_at"],
                name="agent_deploy_tenant_time",
            ),
        ),
        migrations.AddIndex(
            model_name="windowsagentdeployment",
            index=models.Index(
                fields=["status", "created_at"],
                name="agent_deploy_status_time",
            ),
        ),
    ]
