# Generated by Django 6.1 on 2026-09-01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent_pki", "0002_windowsagentdeployment_windowsagentdeploymentsecret_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="windowsagentdeployment",
            name="certificate_trust_mode",
            field=models.CharField(
                choices=[
                    ("system", "System trust"),
                    ("pinned", "Administrator-approved certificate pin"),
                    ("none", "Not applicable"),
                ],
                default="system",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="windowsagentdeployment",
            name="transport",
            field=models.CharField(
                choices=[
                    ("https", "HTTPS"),
                    ("http", "HTTP with message encryption"),
                ],
                default="https",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="windowsagentdeployment",
            name="certificate_fingerprint_sha256",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
