# File Name: import-security-baselines.py
# Version: v0.1.0 | Created: 2026-09-14 | Last Modified: 2026-09-14
# Author: Alice Endelgard | Organization: Alvestrasza Corporation
# Description: Reproducibly import pinned Microsoft SCT GPO data without executing policy tools.
"""Generate the complete baseline read manifests and native, compiled probe allowlist.

Run with the control-plane Python environment (defusedxml is required). ZIPs are
data only: nothing is extracted, imported as code, or executed. The default is
offline. --download retrieves checksum-pinned packages from download.microsoft.com.
--check compares generated bytes without modifying the generated product files.

Coverage means every instruction in the selected GPO payloads is accounted for,
including unknown instructions. Supplemental installer operations are inventoried
separately; this catalog assesses GPO configuration, not the effects of a script,
runtime enforcement, all user hives, or Active Directory password-policy scope.
"""

from __future__ import annotations

import argparse
from collections import Counter
import csv
import hashlib
import io
import json
from pathlib import Path, PurePosixPath
import re
import struct
import urllib.parse
import urllib.request
import zipfile

from defusedxml import ElementTree as ET


ROOT = Path(__file__).resolve().parents[1]
SCHEMA_VERSION = 1
VERIFIED_AT = "2026-09-14"
SOURCE_URL = "https://www.microsoft.com/en-us/download/details.aspx?id=55319"
OLD_DOWNLOAD = "https://download.microsoft.com/download/8/5/c/85c25433-a1b0-4ffa-9429-7e023e7da8d8/"
NEW_DOWNLOAD = "https://download.microsoft.com/download/e99be2d2-e077-4986-a06b-6078051999dd/"
MAX_ZIP_BYTES = 8 * 1024 * 1024
MAX_EXPANDED_BYTES = 50 * 1024 * 1024
MAX_MEMBER_BYTES = 8 * 1024 * 1024
MAX_MEMBERS = 2000
REG_TYPES = {0: "REG_NONE", 1: "REG_SZ", 2: "REG_EXPAND_SZ", 3: "REG_BINARY", 4: "REG_DWORD",
             5: "REG_DWORD_BIG_ENDIAN", 7: "REG_MULTI_SZ", 11: "REG_QWORD"}
VALUE_TYPES = {1: "string", 4: "dword", 7: "string_list"}

# Package versions are the filenames below, not the aggregate SCT download-page date.
PACKAGES = (
    {"baseline_id": "microsoft-windows-server-2025", "os_build": "26100", "revision": "2602",
     "filename": "Windows Server 2025 Security Baseline - 2602.zip", "base_url": NEW_DOWNLOAD,
     "sha256": "a66dffbe2622c3c4dd70e44a7f2080f362fb2d6f9208c50678671cbb046a286f",
     "raw_counts": {"server": 360, "domain-controller": 375}},
    {"baseline_id": "microsoft-windows-server-2022", "os_build": "20348", "revision": "",
     "filename": "Windows Server 2022 Security Baseline.zip", "base_url": OLD_DOWNLOAD,
     "sha256": "49590cc694626d171fc934fafea6494f13ecd3843086704b7a5b98355909b8e0",
     "raw_counts": {"server": 312, "domain-controller": 331}},
    {"baseline_id": "microsoft-windows-server-2019", "os_build": "17763", "revision": "",
     "filename": "Windows 10 Version 1809 and Windows Server 2019 Security Baseline.zip", "base_url": OLD_DOWNLOAD,
     "sha256": "575ddaf39ef364ea6da678e22b0a988ea316eb240f73fbf618092a02647245bc",
     "raw_counts": {"server": 311, "domain-controller": 325}},
    {"baseline_id": "microsoft-windows-server-2016", "os_build": "14393", "revision": "",
     "filename": "Windows 10 Version 1607 and Windows Server 2016 Security Baseline.zip", "base_url": OLD_DOWNLOAD,
     "sha256": "47a877aa5180161e31a9b7dbeb7b6fba6b841e71bcd88cf2857e03d0e7e710d0",
     "raw_counts": {"server": 303, "domain-controller": 179}},
    {"baseline_id": "microsoft-windows-11-25h2", "os_build": "26200", "revision": "",
     "filename": "Windows 11 v25H2 Security Baseline.zip", "base_url": NEW_DOWNLOAD,
     "sha256": "3517a53030a3e437c9fe00c04274d80965d3527a8eb0514520cba75023c376f7",
     "raw_counts": {"client": 425}},
    {"baseline_id": "microsoft-windows-11-24h2", "os_build": "26100", "revision": "",
     "filename": "Windows 11 v24H2 Security Baseline.zip", "base_url": OLD_DOWNLOAD,
     "sha256": "b75439a231c64edaccaad16a16268d199f56ce78273104e117d893f82cf174a5",
     "raw_counts": {"client": 426}},
    {"baseline_id": "microsoft-windows-11-23h2", "os_build": "22631", "revision": "",
     "filename": "Windows 11 v23H2 Security Baseline.zip", "base_url": OLD_DOWNLOAD,
     "sha256": "2e3a61d0245c16bea51a9ee78cbf0793c88046901cecc0039db0dc84fae7d7b7",
     "raw_counts": {"client": 392}},
    {"baseline_id": "microsoft-windows-10-22h2", "os_build": "19045", "revision": "",
     "filename": "Windows 10 version 22H2 Security Baseline.zip", "base_url": OLD_DOWNLOAD,
     "sha256": "cbda99d18339ed7445566447323bd1da40b3e31ab7a5fdba1dae024517a52e1a",
     "raw_counts": {"client": 366}},
)


def canonical_json(value):
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":")).encode("utf-8")


def digest(value):
    return hashlib.sha256(value).hexdigest()


def decode_text(data):
    return data.decode("utf-16") if data.startswith((b"\xff\xfe", b"\xfe\xff")) else data.decode("utf-8-sig")


def registry_records(data):
    """Strict MS-GPREG parser, preserving delete and key-creation instructions."""
    if len(data) < 8 or data[:4] != b"PReg" or struct.unpack_from("<I", data, 4)[0] != 1:
        raise ValueError("Unsupported Registry.pol header")
    pos = 8
    records = []

    def token(value):
        nonlocal pos
        encoded = value.encode("utf-16-le")
        if data[pos:pos + len(encoded)] != encoded:
            raise ValueError(f"Malformed Registry.pol token at offset {pos}")
        pos += len(encoded)

    def string():
        nonlocal pos
        start = pos
        while pos + 2 <= len(data):
            if data[pos:pos + 2] == b"\x00\x00":
                value = data[start:pos].decode("utf-16-le")
                pos += 2
                return value
            pos += 2
        raise ValueError("Unterminated Registry.pol string")

    def integer():
        nonlocal pos
        if pos + 4 > len(data):
            raise ValueError("Truncated Registry.pol integer")
        value = struct.unpack_from("<I", data, pos)[0]
        pos += 4
        return value

    while pos < len(data):
        start = pos
        token("[")
        key = string()
        token(";")
        name = string()
        token(";")
        reg_type = integer()
        token(";")
        length = integer()
        token(";")
        if length > MAX_MEMBER_BYTES or pos + length > len(data):
            raise ValueError("Registry.pol data length exceeds bounds")
        raw = data[pos:pos + length]
        pos += length
        token("]")
        if reg_type in (4, 5, 11):
            if length != (8 if reg_type == 11 else 4):
                raise ValueError("Invalid Registry.pol integer data size")
            expected = int.from_bytes(raw, "big" if reg_type == 5 else "little")
        elif reg_type in (1, 2, 7):
            text = raw.decode("utf-16-le")
            # String terminators are transport encoding, not a value substring.
            if reg_type == 7:
                expected = text.rstrip("\0").split("\0") if text.rstrip("\0") else []
            else:
                expected = text.removesuffix("\0")
                if "\0" in expected:
                    raise ValueError("Embedded NUL in Registry.pol string value")
        else:
            expected = {"hex": raw.hex()}
        records.append({"kind": "registry", "path": key, "name": name, "expected": expected,
                        "reg_type_number": reg_type, "reg_type": REG_TYPES.get(reg_type, str(reg_type)),
                        "byte_offset": start, "data_size": length})
    return records


def inf_records(data):
    """Preserve every non-metadata INF setting, including unsupported sections."""
    records = []
    section = ""
    for number, raw_line in enumerate(decode_text(data).splitlines(), 1):
        line = raw_line.strip()
        if not line or line.startswith(";"):
            continue
        if line.startswith("[") and line.endswith("]"):
            section = line[1:-1]
            continue
        if section.casefold() in ("unicode", "version"):
            continue
        if section == "Service General Setting":
            fields = next(csv.reader([line], strict=True))
            if len(fields) != 3 or not fields[0] or not re.fullmatch(r"[0-4]", fields[1]):
                raise ValueError("Unexpected service security template shape")
            records.append({"kind": "service", "path": "", "name": fields[0], "section": section,
                            "expected": int(fields[1]), "security_descriptor": fields[2], "line": number})
            continue
        if "=" not in line or not section:
            raise ValueError(f"Unparsed INF record at line {number}")
        name, raw_expected = (item.strip() for item in line.split("=", 1))
        if not name:
            raise ValueError("Empty INF setting name")
        record = {"kind": "unsupported", "path": section, "section": section, "name": name,
                  "expected": raw_expected, "line": number}
        if section == "Registry Values":
            fields = next(csv.reader([raw_expected], strict=True))
            if len(fields) < 2:
                raise ValueError("Registry security-template data is missing")
            reg_type = int(fields[0])
            target, value_name = name.rsplit("\\", 1)
            hive, key = target.split("\\", 1)
            if reg_type == 4:
                if len(fields) != 2 or not re.fullmatch(r"\d+", fields[1]):
                    raise ValueError("Invalid security-template DWORD")
                expected = int(fields[1])
                if expected > 0xffffffff:
                    raise ValueError("Security-template DWORD overflows")
            elif reg_type in (1, 2):
                if len(fields) != 2:
                    raise ValueError("Invalid security-template string")
                expected = fields[1]
            elif reg_type == 7:
                expected = fields[1:]
            else:
                expected = {"fields": fields[1:]}
            record.update(kind="registry", hive=hive, path=key, name=value_name, expected=expected,
                          reg_type_number=reg_type, reg_type=REG_TYPES.get(reg_type, str(reg_type)))
        elif section == "Privilege Rights":
            principals = [item.strip().removeprefix("*") for item in raw_expected.split(",") if item.strip()]
            if all(re.fullmatch(r"S-1-(?:\d+-)*\d+", item) for item in principals):
                record.update(kind="privilege_right", path="", expected=sorted(set(principals)))
        elif section == "System Access":
            if re.fullmatch(r"-?\d+", raw_expected):
                record.update(kind="system_access", path="", expected=int(raw_expected))
        records.append(record)
    return records


def audit_records(data):
    expected_headers = ["Machine Name", "Policy Target", "Subcategory", "Subcategory GUID",
                        "Inclusion Setting", "Exclusion Setting", "Setting Value"]
    reader = csv.DictReader(io.StringIO(decode_text(data)), strict=True)
    if reader.fieldnames != expected_headers:
        raise ValueError("Unexpected audit CSV schema")
    records = []
    for number, row in enumerate(reader, 2):
        if set(row) != set(expected_headers) or any(value is None for value in row.values()):
            raise ValueError("Malformed audit CSV row")
        guid = row["Subcategory GUID"].casefold()
        if not re.fullmatch(r"\{[0-9a-f]{8}-(?:[0-9a-f]{4}-){3}[0-9a-f]{12}\}", guid):
            raise ValueError("Invalid audit subcategory GUID")
        if not re.fullmatch(r"[0-3]", row["Setting Value"]):
            raise ValueError("Invalid audit inclusion mask")
        records.append({"kind": "audit", "path": guid, "name": row["Subcategory"],
                        "expected": int(row["Setting Value"]), "target": row["Policy Target"],
                        "exclusion": row["Exclusion Setting"], "line": number})
    return records


def safe_archive(data):
    if len(data) > MAX_ZIP_BYTES:
        raise ValueError("SCT ZIP exceeds size limit")
    archive = zipfile.ZipFile(io.BytesIO(data))
    members = archive.infolist()
    names = set()
    if len(members) > MAX_MEMBERS or sum(item.file_size for item in members) > MAX_EXPANDED_BYTES:
        raise ValueError("SCT archive exceeds expanded size or entry limit")
    for item in members:
        path = PurePosixPath(item.filename)
        normalized = item.filename.casefold()
        if (path.is_absolute() or ".." in path.parts or "\\" in item.filename or ":" in item.filename
                or normalized in names or item.file_size > MAX_MEMBER_BYTES or item.flag_bits & 1):
            raise ValueError("Unsafe or duplicate SCT ZIP member")
        names.add(normalized)
    if archive.testzip() is not None:
        raise ValueError("SCT archive CRC mismatch")
    return archive


def package_url(package):
    return package["base_url"] + urllib.parse.quote(package["filename"])


def download_package(package, directory):
    """Fetch immutable, hash-pinned data; reject redirects to other hosts."""
    class MicrosoftOnlyRedirect(urllib.request.HTTPRedirectHandler):
        def redirect_request(self, request, fp, code, msg, headers, newurl):
            parsed = urllib.parse.urlsplit(newurl)
            if parsed.scheme != "https" or parsed.hostname != "download.microsoft.com":
                raise ValueError("SCT download redirected outside download.microsoft.com")
            return super().redirect_request(request, fp, code, msg, headers, newurl)

    request = urllib.request.Request(package_url(package), headers={"User-Agent": "IPMS-SCT-Content-Importer/1"})
    with urllib.request.build_opener(MicrosoftOnlyRedirect).open(request, timeout=60) as response:
        data = response.read(MAX_ZIP_BYTES + 1)
    if len(data) > MAX_ZIP_BYTES or digest(data) != package["sha256"]:
        raise ValueError(f"Package checksum or size mismatch: {package['baseline_id']}")
    with safe_archive(data):
        pass
    directory.mkdir(parents=True, exist_ok=True)
    (directory / (package["baseline_id"] + ".zip")).write_bytes(data)


def profile_selection(archive, components, baseline_id, profile):
    """Read the pinned installer as data; support only its verified literal subset."""
    names = archive.namelist()
    by_name = {component["name"]: component["id"] for component in components.values()}
    if len(by_name) != len(components):
        raise ValueError("Ambiguous GPO display name")
    if baseline_id == "microsoft-windows-server-2016":
        suffix = "Member_Server_Install.cmd" if profile == "server" else "Domain_Controller_Install.cmd"
        candidates = [name for name in names if name.endswith("/" + suffix)]
        if len(candidates) != 1:
            raise ValueError("Missing Windows Server 2016 installer")
        source = candidates[0]
        text = decode_text(archive.read(source))
        selected = re.findall(r"(?im)^Tools\\LGPO\.exe\s+/v\s+/g\s+\.\.\\GPOs\\(\{[0-9A-F-]+\})", text)
        ordering = "installer-statement-order"
        expected = 7 if profile == "server" else 4
    else:
        candidates = [name for name in names if name.casefold().endswith(("/baseline-localinstall.ps1", "/baselinelocalinstall.ps1"))]
        if len(candidates) != 1:
            raise ValueError("Missing baseline PowerShell installer")
        source = candidates[0]
        text = decode_text(archive.read(source)).replace("\r", "")
        definitions = dict(re.findall(r'^\$(GPO_\w+)\s*=\s*"([^"\r\n]+)"', text, re.MULTILINE))
        sections = re.split(r"(?m)^# GPOs for ", text)
        if profile == "client":
            chosen = [part for part in sections[1:] if re.match(r"Windows (?:10|11)\n", part)]
        elif profile == "server":
            chosen = [part for part in sections[1:] if re.match(r"Windows Server(?: 2019)? \(not Domain Controller\)\n", part)]
        else:
            chosen = [part for part in sections[1:] if re.match(r"Windows Server(?: 2019)? Domain Controller\n", part)]
        if len(chosen) != 1 or not re.search(r"\$GPOs\.Keys\s*\|\s*Sort-Object\s*\|\s*foreach", text):
            raise ValueError("Unrecognized baseline installer profile or order")
        variables = re.findall(r"(?m)^\s*AddToCollection\s+\$GPOs\s+\$(GPO_\w+)\s*$", chosen[0])
        selected_names = [definitions[name] for name in variables]
        # The pinned English display names use ASCII; their ordering is unambiguous.
        selected = [by_name[name] for name in sorted(selected_names, key=str.casefold)]
        ordering = "installer-display-name-sort"
        expected = 8 if profile == "client" else 6
    if len(selected) != expected or len(set(selected)) != expected or any(item not in components for item in selected):
        raise ValueError("Baseline installer selected missing or unexpected GPOs")
    return selected, {"source_path": source, "source_sha256": digest(archive.read(source)), "order": ordering,
                      "selection": "domain-joined-gpo-composition", "selected_component_ids": selected}


def read_components(archive):
    components = {}
    names = archive.namelist()
    parsed_payloads = set()
    for source in names:
        if not source.casefold().endswith("/bkupinfo.xml"):
            continue
        metadata = ET.fromstring(archive.read(source))
        display_nodes = [node.text for node in metadata.iter() if node.tag.rsplit("}", 1)[-1] == "GPODisplayName"]
        if len(display_nodes) != 1 or not display_nodes[0]:
            raise ValueError("Missing GPO display metadata")
        prefix = source.rsplit("/", 1)[0] + "/"
        component_id = prefix.rstrip("/").rsplit("/", 1)[-1]
        if component_id in components:
            raise ValueError("Duplicate GPO component ID")
        component = {"id": component_id, "name": display_nodes[0], "files": [], "records": []}
        gpo_prefix = prefix + "DomainSysvol/GPO/"
        for member in sorted(name for name in names if name.startswith(gpo_prefix) and not name.endswith("/")):
            relative = member[len(gpo_prefix):]
            data = archive.read(member)
            file_hash = digest(data)
            if relative.casefold().endswith("comment.cmtx"):
                component["files"].append({"path": member, "sha256": file_hash, "role": "comment-metadata", "records": 0})
                parsed_payloads.add(member)
                continue
            lower = relative.casefold()
            if lower.endswith("/registry.pol"):
                parsed, source_format = registry_records(data), "registry.pol"
            elif lower.endswith("/gpttmpl.inf"):
                parsed, source_format = inf_records(data), "security-template"
            elif lower.endswith("/audit.csv"):
                parsed, source_format = audit_records(data), "audit.csv"
            else:
                raise ValueError(f"Unaccounted GPO payload: {member}")
            scope = "user" if relative.casefold().startswith("user/") else "machine"
            if "domain security" in component["name"].casefold():
                scope = "domain"
            for index, record in enumerate(parsed):
                record.update(scope=scope, component_id=component_id, component_name=component["name"],
                              source_path=member, source_record=index, source_sha256=file_hash, source_format=source_format)
            component["records"].extend(parsed)
            component["files"].append({"path": member, "sha256": file_hash, "role": source_format, "records": len(parsed)})
            parsed_payloads.add(member)
        components[component_id] = component
    all_payloads = {name for name in names if "/domainsysvol/gpo/" in name.casefold() and not name.endswith("/")}
    if not components or all_payloads != parsed_payloads:
        raise ValueError("GPO payload inventory is incomplete")
    return components


def normalized_control(record):
    control = {"kind": record["kind"], "scope": record["scope"], "path": record["path"], "name": record["name"],
               "value_type": "", "expected": record["expected"], "comparison": "equals", "label": record["name"]}
    reason = ""
    if control["kind"] == "registry":
        control["value_type"] = VALUE_TYPES.get(record["reg_type_number"], "")
        control["registry_type"] = record["reg_type"]
        if record.get("hive", "MACHINE").casefold() != "machine":
            reason = "Unsupported security-template registry hive"
        elif control["name"].casefold().startswith("**del.") and len(control["name"]) > 6:
            control.update(name=control["name"][6:], expected=None, comparison="absent")
            control["label"] = "Absent registry value: " + control["name"]
        elif control["name"].startswith("**"):
            reason = "Registry bulk deletion, list reset, or security directive requires final-key semantics"
        elif record["reg_type_number"] == 0 and not control["name"] and not record.get("data_size"):
            reason = "Registry key-creation instruction is not a default-value assertion"
        elif not control["value_type"]:
            reason = "Registry value type is not supported by the native read contract"
    elif control["kind"] == "audit":
        control["value_type"] = "dword"
        if record["target"].casefold() != "system" or record["exclusion"]:
            reason = "Only system audit inclusion masks are supported"
    elif control["kind"] == "privilege_right":
        control["value_type"] = "string_list"
    elif control["kind"] == "system_access":
        control["value_type"] = "dword"
    elif control["kind"] == "service":
        control["value_type"] = "dword"
        if record["security_descriptor"]:
            reason = "Service security descriptors require a separate ACL comparison"
        # Blank SDDL in this INF section means no ACL assertion, not an empty ACL.
    else:
        reason = "Unsupported security-template instruction or unresolved account name"
    if reason:
        control.update(kind="unsupported", comparison="unsupported", unsupported_reason=reason)
        if isinstance(control["expected"], dict):
            # Opaque unsupported bytes remain in source provenance, not wire/UI values.
            control["expected"] = None
    elif control["scope"] != "machine":
        control["unsupported_reason"] = "User or domain scope cannot be established by a local machine read"
    provenance = {key: record[key] for key in ("component_id", "source_path", "source_record", "source_sha256", "source_format")}
    for key in ("byte_offset", "line", "section"):
        if key in record:
            provenance[key] = record[key]
    provenance["original"] = {key: record[key] for key in ("kind", "path", "name", "expected")}
    for key in ("reg_type", "security_descriptor", "exclusion", "target"):
        if key in record:
            provenance["original"][key] = record[key]
    provenance["resolution"] = "effective"
    control.update(source_components=[record["component_id"]], source_records=[provenance])
    return control


def control_identity(control):
    # Registry names/paths and security-policy field names are case insensitive.
    return (control["kind"], control["scope"], control["path"].casefold(),
            control["path"].casefold() if control["kind"] == "audit" else control["name"].casefold())


def normalize_controls(records, baseline_id, profile):
    """Last installer component wins; retain every original record and resolution."""
    result = {}
    for record in records:
        control = normalized_control(record)
        identity = control_identity(control)
        previous = result.get(identity)
        if previous:
            equivalent = all(previous[key] == control[key] for key in ("comparison", "value_type", "expected"))
            same_component = previous["source_records"][-1]["component_id"] == record["component_id"]
            if not equivalent and same_component and previous["source_records"][-1]["source_path"] != record["source_path"]:
                # Extension ordering inside a single GPO cannot be inferred from ZIP entry order.
                raise ValueError("Conflicting GPO extensions require an explicit precedence rule")
            for prior in previous["source_records"]:
                if prior["resolution"] == "effective":
                    prior["resolution"] = "equivalent" if equivalent else "overridden"
            control["source_records"] = previous["source_records"] + control["source_records"]
            control["source_components"] = list(dict.fromkeys(previous["source_components"] + control["source_components"]))
        result[identity] = control
    controls = []
    for identity in sorted(result):
        control = result[identity]
        control["id"] = "ctrl-" + digest(canonical_json([baseline_id, profile, *identity]))[:24]
        controls.append(control)
    if len({control["id"] for control in controls}) != len(controls):
        raise ValueError("Control identifier collision")
    if sum(len(control["source_records"]) for control in controls) != len(records):
        raise ValueError("Source instruction accounting mismatch")
    return controls


def supplemental_inventory(archive):
    entries = []
    for name in sorted(archive.namelist()):
        if name.endswith("/") or "/configfiles/" not in name.casefold():
            continue
        entries.append({"path": name, "sha256": digest(archive.read(name)), "scope": "non-gpo-installer-data",
                        "reason": "Supplemental installer input is outside the selected GPO configuration scope"})
    return entries


def reference_signature(record):
    """Compare source GPO instructions with Microsoft's independent PolicyRules export."""
    expected = record["expected"]
    if record["kind"] == "registry" and (record["name"].casefold().startswith("**del.") or record["name"].casefold() == "**delvals."):
        # The deletion target is meaningful; the directive's placeholder data is not.
        expected = None
    if isinstance(expected, str):
        # Policy Analyzer renders embedded line endings as literal display escapes.
        # This is only the reference comparison; manifest values retain exact CR/LF.
        expected = expected.replace("\r", "\\r").replace("\n", "\\n")
    return (record["component_name"], record["source_format"], record["kind"], record["path"].casefold(),
            "" if record["kind"] == "audit" else record["name"].casefold(), record.get("reg_type", ""),
            canonical_json(expected))


def policy_rules_inventory(archive, components):
    entries = []
    for name in sorted(archive.namelist()):
        if not name.casefold().endswith(".policyrules"):
            continue
        root = ET.fromstring(archive.read(name))
        counts = Counter(child.tag.rsplit("}", 1)[-1] for child in root)
        allowed = {"ComputerConfig", "UserConfig", "SecurityTemplate", "AuditSubcategory", "CSE-Machine", "CSE-User"}
        if set(counts) - allowed:
            raise ValueError("Unrecognized PolicyRules instruction kind")
        reference_records = []
        extension_metadata = []
        for child in root:
            tag = child.tag.rsplit("}", 1)[-1]
            if tag in ("CSE-Machine", "CSE-User"):
                extension_metadata.append({"scope": "machine" if tag == "CSE-Machine" else "user",
                                           "guid": child.findtext("GUID"), "name": child.findtext("Name")})
                continue
            component_name = child.findtext("PolicyName")
            if not component_name:
                raise ValueError("PolicyRules reference has no component name")
            if tag in ("ComputerConfig", "UserConfig"):
                reg_type = child.findtext("RegType")
                data = child.findtext("RegData", "")
                if reg_type == "REG_DWORD":
                    expected = int(data)
                elif reg_type == "REG_SZ":
                    expected = data
                elif reg_type == "REG_NONE" and not data:
                    expected = {"hex": ""}
                else:
                    raise ValueError("Unsupported PolicyRules registry representation")
                record = {"kind": "registry", "path": child.findtext("Key", ""), "name": child.findtext("Value", ""),
                          "reg_type": reg_type, "expected": expected, "source_format": "registry.pol"}
            elif tag == "SecurityTemplate":
                section = child.get("Section")
                line = child.findtext("LineItem")
                if not section or not line:
                    raise ValueError("Incomplete PolicyRules security-template reference")
                parsed = inf_records(("[" + section + "]\n" + line).encode("utf-8"))
                if len(parsed) != 1:
                    raise ValueError("PolicyRules security-template record is not singular")
                record = {**parsed[0], "source_format": "security-template"}
            else:
                record = {"kind": "audit", "path": child.findtext("GUID", "").casefold(), "name": child.findtext("Name", ""),
                          "expected": int(child.findtext("Setting", "")), "source_format": "audit.csv"}
            record["component_name"] = component_name
            reference_records.append(record)
        selected_names = {record["component_name"] for record in reference_records}
        source_records = [record for component in components.values() if component["name"] in selected_names for record in component["records"]]
        if Counter(map(reference_signature, source_records)) != Counter(map(reference_signature, reference_records)):
            raise ValueError(f"PolicyRules reference does not match parsed GPO data: {name}")
        entries.append({"path": name, "sha256": digest(archive.read(name)), "counts": dict(sorted(counts.items())),
                        "role": "reference-export-of-gpo-data-and-extension-metadata", "matched_instruction_count": len(reference_records),
                        "crosscheck": "all-referenced-gpo-instructions-match", "extension_metadata": extension_metadata})
    return entries


def build_catalog(package_directory):
    manifests = []
    for package in PACKAGES:
        data = (package_directory / (package["baseline_id"] + ".zip")).read_bytes()
        if digest(data) != package["sha256"]:
            raise ValueError(f"Unpinned package content: {package['baseline_id']}")
        with safe_archive(data) as archive:
            components = read_components(archive)
            for profile in package["raw_counts"]:
                selected, selection = profile_selection(archive, components, package["baseline_id"], profile)
                records = [record for identifier in selected for record in components[identifier]["records"]]
                if len(records) != package["raw_counts"][profile]:
                    raise ValueError(f"Pinned GPO instruction count changed: {package['baseline_id']}/{profile}")
                controls = normalize_controls(records, package["baseline_id"], profile)
                manifest = {
                    "schema_version": SCHEMA_VERSION, "baseline_id": package["baseline_id"], "profile": profile,
                    "os_build": package["os_build"], "revision": package["revision"], "verified_at": VERIFIED_AT,
                    "assessment_scope": "complete-selected-gpo-configuration",
                    "source_url": SOURCE_URL, "source_package_url": package_url(package),
                    "source_package_name": package["filename"], "source_package_sha256": package["sha256"],
                    "selection": selection,
                    "components": [{key: components[identifier][key] for key in ("id", "name", "files")} for identifier in selected],
                    "excluded_components": [{"id": component["id"], "name": component["name"], "raw_records": len(component["records"]),
                                              "reason": "Not selected by this profile in the Microsoft installer"}
                                             for identifier, component in sorted(components.items()) if identifier not in selected],
                    "supplemental_config_files": supplemental_inventory(archive),
                    "policy_rules_references": policy_rules_inventory(archive, components),
                    "limitations": [
                        "User policy and Domain Security scope remain unknown without corresponding scope evidence.",
                        "Registry values assess configured policy; they do not establish runtime feature enforcement.",
                        "The composition is domain joined; non-domain-joined installer deltas are outside this manifest.",
                        "Administrative-template copying, extension registration, scheduled tasks, and exploit-protection script actions are outside GPO configuration scope.",
                        "Unsupported instructions remain controls with unknown results; they never imply compliance.",
                    ],
                    "coverage": {
                        "raw_instruction_count": len(records), "accounted_instruction_count": sum(len(c["source_records"]) for c in controls),
                        "control_count": len(controls), "package_raw_instruction_count": sum(len(c["records"]) for c in components.values()),
                        "kinds": dict(sorted(Counter(c["kind"] for c in controls).items())),
                        "scopes": dict(sorted(Counter(c["scope"] for c in controls).items())),
                        "equivalent_instruction_count": sum(r["resolution"] == "equivalent" for c in controls for r in c["source_records"]),
                        "overridden_instruction_count": sum(r["resolution"] == "overridden" for c in controls for r in c["source_records"]),
                    },
                    "controls": controls,
                }
                manifest["manifest_sha256"] = digest(canonical_json(manifest))
                manifests.append(manifest)
    manifests.sort(key=lambda item: (item["baseline_id"], item["profile"]))
    return manifests, digest(canonical_json(manifests))


def native_probe(control):
    if control["scope"] != "machine" or control["comparison"] == "unsupported":
        return "unsupported"
    return {"registry": "registry_value", "audit": "audit_policy", "privilege_right": "user_right",
            "system_access": "account_policy", "service": "service_start"}.get(control["kind"], "unsupported")


def render_python(manifests, catalog_hash):
    # JSON is data, not eval. No untrusted package executable code is emitted.
    payload = json.dumps(manifests, ensure_ascii=False, sort_keys=True, indent=2)
    if "'''" in payload:
        raise ValueError("Generated JSON requires another Python literal delimiter")
    return (
        "# File Name: content.py\n"
        "# Version: v0.1.0 | Created: 2026-09-14 | Last Modified: 2026-09-14\n"
        "# Author: Alice Endelgard | Organization: Alvestrasza Corporation\n"
        "# Description: Generated Microsoft SCT GPO manifests; regenerate with scripts/import-security-baselines.py.\n"
        "# Do not edit. Hashes use UTF-8 JSON, sorted keys, compact separators, ensure_ascii=False.\n"
        "import hashlib\nimport json\n\n"
        f"CATALOG_SHA256 = {catalog_hash!r}\n"
        "MANIFEST_SCHEMA_VERSION = 1\n\n"
        "_MANIFEST_DATA = json.loads(r'''\n" + payload + "\n''')\n\n"
        "if hashlib.sha256(json.dumps(_MANIFEST_DATA, ensure_ascii=False, sort_keys=True, separators=(',', ':')).encode('utf-8')).hexdigest() != CATALOG_SHA256:\n"
        "    raise RuntimeError('Security baseline manifest integrity check failed')\n"
        "MANIFESTS = {(item['baseline_id'], item['profile']): item for item in _MANIFEST_DATA}\n"
        "del _MANIFEST_DATA\n"
    ).encode("utf-8")


def render_header(manifests, catalog_hash):
    lines = [
        "// File Name: security_baseline_content.hpp",
        "// Version: v0.1.0 | Created: 2026-09-14 | Last Modified: 2026-09-14",
        "// Author: Alice Endelgard | Organization: Alvestrasza Corporation",
        "// Description: Generated Microsoft SCT read-only probe allowlist; do not edit.",
        "#pragma once", "", '#include "ipms/agent/security_baseline.hpp"', "",
        "namespace ipms::agent::security {", "",
        f'inline constexpr char catalog_sha256[] = "{catalog_hash}";', "",
    ]
    for index, manifest in enumerate(manifests):
        lines.append(f"inline constexpr control_descriptor profile_{index}_controls[] = {{")
        for control in manifest["controls"]:
            values = [json.dumps(control[key], ensure_ascii=True) for key in ("id", "scope", "path", "name", "value_type")]
            lines.append(f"    {{{values[0]}, probe_kind::{native_probe(control)}, " + ", ".join(values[1:]) + "},")
        lines.extend(["};", ""])
    lines.append("inline constexpr baseline_descriptor baselines[] = {")
    for index, manifest in enumerate(manifests):
        values = [json.dumps(manifest[key], ensure_ascii=True) for key in ("baseline_id", "profile", "manifest_sha256", "os_build")]
        lines.append("    {" + ", ".join(values) + f", std::span<const control_descriptor>{{profile_{index}_controls}}" + "},")
    lines.extend(["};", "", "} // namespace ipms::agent::security", ""])
    return "\n".join(lines).encode("utf-8")


def generated_files(manifests, catalog_hash):
    return {
        Path("services/control-plane/src/ipms/apps/security/content.py"): render_python(manifests, catalog_hash),
        Path("agent/include/ipms/agent/security_baseline_content.hpp"): render_header(manifests, catalog_hash),
    }


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--package-dir", type=Path, default=ROOT / "build/security-content")
    parser.add_argument("--output-root", type=Path, default=ROOT)
    parser.add_argument("--download", action="store_true", help="Download missing checksum-pinned Microsoft ZIPs as data")
    parser.add_argument("--check", action="store_true", help="Verify generated bytes without writing product files")
    args = parser.parse_args(argv)
    if args.download:
        for package in PACKAGES:
            if not (args.package_dir / (package["baseline_id"] + ".zip")).exists():
                download_package(package, args.package_dir)
    manifests, catalog_hash = build_catalog(args.package_dir)
    mismatches = []
    for relative, data in generated_files(manifests, catalog_hash).items():
        path = args.output_root / relative
        if args.check:
            if not path.exists() or path.read_bytes() != data:
                mismatches.append(relative.as_posix())
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data)
    for manifest in manifests:
        print(json.dumps({"baseline_id": manifest["baseline_id"], "profile": manifest["profile"],
                          "manifest_sha256": manifest["manifest_sha256"], "coverage": manifest["coverage"]}, separators=(",", ":")))
    print(json.dumps({"catalog_sha256": catalog_hash, "profiles": len(manifests), "mismatches": mismatches}, separators=(",", ":")))
    return 1 if mismatches else 0


if __name__ == "__main__":
    raise SystemExit(main())
