# Generated by Django 6.1 on 2026-08-31 12:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discovery", "0007_bmceventlogentry"),
        ("tenancy", "0002_tenantmembership"),
    ]

    operations = [
        migrations.CreateModel(
            name="WindowsServer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source_id", models.CharField(max_length=255)),
                (
                    "inventory_source",
                    models.CharField(
                        choices=[("agent", "IPMS Agent"), ("hyper-v", "Hyper-V")],
                        max_length=16,
                    ),
                ),
                (
                    "server_type",
                    models.CharField(
                        choices=[
                            ("physical", "Physical"),
                            ("virtual", "Virtual"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                ("hostname", models.CharField(max_length=255)),
                ("fqdn", models.CharField(blank=True, max_length=255)),
                ("domain_name", models.CharField(blank=True, max_length=255)),
                ("operating_system", models.CharField(blank=True, max_length=255)),
                ("os_version", models.CharField(blank=True, max_length=128)),
                ("os_build", models.CharField(blank=True, max_length=64)),
                ("architecture", models.CharField(blank=True, max_length=32)),
                ("manufacturer", models.CharField(blank=True, max_length=255)),
                ("model", models.CharField(blank=True, max_length=255)),
                ("serial_number", models.CharField(blank=True, max_length=255)),
                ("system_uuid", models.CharField(blank=True, max_length=64)),
                (
                    "logical_processors",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("memory_bytes", models.PositiveBigIntegerField(blank=True, null=True)),
                ("cluster_name", models.CharField(blank=True, max_length=255)),
                ("hypervisor_host", models.CharField(blank=True, max_length=255)),
                ("agent_version", models.CharField(blank=True, max_length=64)),
                (
                    "agent_state",
                    models.CharField(
                        choices=[
                            ("not-enrolled", "Not enrolled"),
                            ("online", "Online"),
                            ("stale", "Stale"),
                            ("offline", "Offline"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                (
                    "health",
                    models.CharField(
                        choices=[
                            ("healthy", "Healthy"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                ("management_packs", models.JSONField(blank=True, default=list)),
                ("detail_snapshot", models.JSONField(blank=True, default=dict)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("discovered_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="windows_servers",
                        to="discovery.connectorendpoint",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="windows_servers",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ("hostname",),
                "indexes": [
                    models.Index(
                        fields=["tenant", "server_type"],
                        name="windows_tenant_type_idx",
                    ),
                    models.Index(
                        fields=["tenant", "agent_state"],
                        name="windows_tenant_agent_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "inventory_source", "source_id"),
                        name="unique_tenant_windows_source",
                    )
                ],
            },
        ),
    ]
