# Generated by Django 6.1 on 2026-09-01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discovery", "0008_windowsserver"),
    ]

    operations = [
        migrations.AddField(
            model_name="windowsserver",
            name="network_interfaces",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name="WindowsServerTelemetry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cpu_used_percent", models.PositiveSmallIntegerField()),
                ("memory_total_bytes", models.PositiveBigIntegerField()),
                ("memory_available_bytes", models.PositiveBigIntegerField()),
                ("memory_used_bytes", models.PositiveBigIntegerField()),
                ("memory_used_percent", models.PositiveSmallIntegerField()),
                ("fixed_volumes", models.JSONField(blank=True, default=list)),
                ("observed_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "server",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="latest_telemetry",
                        to="discovery.windowsserver",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="windows_server_telemetry",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant", "-observed_at"],
                        name="wintelemetry_tenant_time_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("cpu_used_percent__lte", 100)),
                        name="wintelemetry_cpu_percent_lte_100",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("memory_used_percent__lte", 100)),
                        name="wintelemetry_memory_percent_lte_100",
                    ),
                ],
            },
        ),
    ]
