# Generated by Django 6.1 on 2026-09-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discovery", "0009_windowsserver_telemetry"),
    ]

    operations = [
        migrations.AddField(
            model_name="windowsserver",
            name="installed_roles_features",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="windowsserver",
            name="installed_roles_features_status",
            field=models.CharField(
                choices=[
                    ("not-reported", "Not reported"),
                    ("collected", "Collected"),
                    ("unavailable", "Unavailable"),
                ],
                default="not-reported",
                max_length=16,
            ),
        ),
    ]
