# Generated by Django 6.1 on 2026-09-04 00:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_pki", "0006_agent_enrollment_removed_status"),
        ("discovery", "0014_hyperv_virtual_machine_inventory"),
        ("tenancy", "0002_tenantmembership"),
    ]

    operations = [
        migrations.CreateModel(
            name="SoftwareInventorySnapshot",
            fields=[
                ("id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("platform", models.CharField(choices=[("windows", "Windows"), ("linux", "Linux")], max_length=16)),
                ("status", models.CharField(choices=[("receiving", "Receiving"), ("completed", "Completed")], default="receiving", max_length=16)),
                ("page_count", models.PositiveSmallIntegerField()),
                ("received_pages", models.JSONField(blank=True, default=list)),
                ("reboot_required", models.BooleanField(blank=True, null=True)),
                ("update_scan_status", models.CharField(default="unknown", max_length=32)),
                ("last_update_scan_at", models.DateTimeField(blank=True, null=True)),
                ("last_update_install_at", models.DateTimeField(blank=True, null=True)),
                ("package_count", models.PositiveIntegerField(default=0)),
                ("updates_available", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("enrollment", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="software_inventory_snapshots", to="agent_pki.agentenrollment")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="software_inventory_snapshots", to="tenancy.tenant")),
            ],
            options={"ordering": ("-created_at",)},
        ),
        migrations.CreateModel(
            name="SoftwarePackage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("source_id", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("installed_version", models.CharField(blank=True, max_length=255)),
                ("available_version", models.CharField(blank=True, max_length=255)),
                ("publisher", models.CharField(blank=True, max_length=255)),
                ("package_type", models.CharField(max_length=32)),
                ("update_state", models.CharField(choices=[("current", "Current"), ("update-available", "Update available"), ("unknown", "Unknown")], default="unknown", max_length=24)),
                ("is_os_component", models.BooleanField(default=False)),
                ("snapshot", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="packages", to="discovery.softwareinventorysnapshot")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="software_packages", to="tenancy.tenant")),
            ],
            options={"ordering": ("name", "source_id")},
        ),
        migrations.CreateModel(
            name="LinuxSystem",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("inventory_source", models.CharField(default="agent", max_length=32)),
                ("source_id", models.CharField(max_length=64)),
                ("hostname", models.CharField(max_length=255)),
                ("fqdn", models.CharField(max_length=255)),
                ("system_type", models.CharField(choices=[("physical", "Physical"), ("virtual", "Virtual"), ("unknown", "Unknown")], default="unknown", max_length=16)),
                ("distribution", models.CharField(blank=True, max_length=255)),
                ("distribution_version", models.CharField(blank=True, max_length=128)),
                ("kernel_version", models.CharField(blank=True, max_length=128)),
                ("architecture", models.CharField(blank=True, max_length=32)),
                ("manufacturer", models.CharField(blank=True, max_length=255)),
                ("model", models.CharField(blank=True, max_length=255)),
                ("serial_number", models.CharField(blank=True, max_length=255)),
                ("logical_processors", models.PositiveIntegerField(blank=True, null=True)),
                ("memory_bytes", models.PositiveBigIntegerField(blank=True, null=True)),
                ("agent_version", models.CharField(max_length=32)),
                ("health", models.CharField(choices=[("healthy", "Healthy"), ("warning", "Warning"), ("critical", "Critical"), ("unknown", "Unknown")], default="unknown", max_length=16)),
                ("network_interfaces", models.JSONField(blank=True, default=list)),
                ("fixed_volumes", models.JSONField(blank=True, default=list)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="linux_systems", to="tenancy.tenant")),
            ],
            options={
                "ordering": ("fqdn", "hostname"),
                "indexes": [models.Index(fields=["tenant", "system_type"], name="linux_tenant_type_idx")],
                "constraints": [models.UniqueConstraint(fields=("tenant", "inventory_source", "source_id"), name="unique_linux_inventory_source")],
            },
        ),
        migrations.AddIndex(
            model_name="softwareinventorysnapshot",
            index=models.Index(fields=["tenant", "enrollment", "status"], name="software_snapshot_lookup_idx"),
        ),
        migrations.AddIndex(
            model_name="softwarepackage",
            index=models.Index(fields=["tenant", "update_state"], name="software_tenant_update_idx"),
        ),
        migrations.AddConstraint(
            model_name="softwarepackage",
            constraint=models.UniqueConstraint(fields=("snapshot", "source_id"), name="unique_snapshot_software_package"),
        ),
    ]
