# Generated by Django 6.1 on 2026-09-04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discovery", "0017_hypervvirtualmachineactionjob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hypervvirtualmachineactionjob",
            name="action",
            field=models.CharField(
                choices=[
                    ("start", "Start"),
                    ("shutdown", "Shut down"),
                    ("stop", "Stop"),
                    ("pause", "Pause"),
                    ("resume", "Resume"),
                ],
                max_length=16,
            ),
        ),
    ]
